// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddInventoryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addInventory() {
    // Test name: Add Inventory
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://yellowb02app-env.eba-a62escia.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 992x694 |  | 
    driver.manage().window().setSize(new Dimension(992, 694));
    // 3 | click | css=.content |  | 
    driver.findElement(By.cssSelector(".content")).click();
    // 4 | click | linkText=Inventory |  | 
    driver.findElement(By.linkText("Inventory")).click();
    // 5 | click | id=itemname |  | 
    driver.findElement(By.id("itemname")).click();
    // 6 | type | id=itemname | Test item | 
    driver.findElement(By.id("itemname")).sendKeys("Test item");
    // 7 | click | id=sku |  | 
    driver.findElement(By.id("sku")).click();
    // 8 | type | id=sku | AU3787OPS | 
    driver.findElement(By.id("sku")).sendKeys("AU3787OPS");
    // 9 | click | id=price |  | 
    driver.findElement(By.id("price")).click();
    // 10 | type | id=price | 12 | 
    driver.findElement(By.id("price")).sendKeys("12");
    // 11 | click | id=quantity |  | 
    driver.findElement(By.id("quantity")).click();
    // 12 | type | id=quantity | 5 | 
    driver.findElement(By.id("quantity")).sendKeys("5");
    // 13 | click | id=description |  | 
    driver.findElement(By.id("description")).click();
    // 14 | type | id=description | this is a test | 
    driver.findElement(By.id("description")).sendKeys("this is a test");
    // 15 | click | id=submit |  | 
    driver.findElement(By.id("submit")).click();
    // 16 | close |  |  | 
    driver.close();
  }
}
